name: Update GH pages

on:
  workflow_dispatch: {}

concurrency:
  group: update-data-${{ github.head_ref || github.ref }}
  cancel-in-progress: true


jobs:
  update-data:
    name: "Update Data"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: wyvox/action@v1
      - run: node ./index.js
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEV_TO_KEY: ${{ secrets.DEV_TO_KEY }}
      # - run: |
      #     cp index.html ./dist/
      #     cd dist
      #     git config --global user.email "actions@github.com"
      #     git config --global user.name "github-actions[bot]"
      #     git config --global init.defaultBranch gh-pages
      #     git init

      #     git remote add origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
      #     git add .
      #     git commit -am"'deploy'"
      #     git push --set-upstream origin gh-pages --force
      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: dist      #directory to generate index

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: 'dist'      # upload generated folder
  
  deploy:
    needs: update-data
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.0

