name: Update GH pages

on:
  workflow_dispatch: {}

concurrency:
  group: update-data-${{ github.head_ref || github.ref }}
  cancel-in-progress: true


jobs:
  update-data:
    name: "Update Data"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: wyvox/action@v1
      - run: node ./index.js
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEV_TO_KEY: ${{ secrets.DEV_TO_KEY }}
      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
      - run: pnpm gh-pages -d dist
