name: Update GH pages

on:
  workflow_dispatch: {}

concurrency:
  group: update-data-${{ github.head_ref || github.ref }}
  cancel-in-progress: true


jobs:
  update-data:
    name: "Update Data"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: wyvox/action@v1
      - run: node ./index.js
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEV_TO_KEY: ${{ secrets.DEV_TO_KEY }}
      - run: |
          cp index.html ./dist/
          cd dist
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git config --global init.defaultBranch gh-pages
          git init

          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git add .
          git commit -am"'deploy'"
          git push -f

